package com.cib.model;

import java.util.Date;

/**
 * 地区插页规则实体--地区插页规则表
 * ActionRule2 generated by MyEclipse Persistence Tools
 */

public class ActionRule2 implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 591141705888689909L;
	private Long advActionId;
	private String advActionName;

	private String locInstId;

	private String locInstName;

	private String CCity;

	private String creatAuthor;

	private Date crateDatetime;

	private String chgAuthor;

	private Date chgDatetime;

	// Constructors

	/** default constructor */
	public ActionRule2() {
	}

	/** full constructor */
	public ActionRule2(Long advActionId, String advActionName,
			String locInstId, String locInstName, String CCity,
			String creatAuthor, Date crateDatetime, String chgAuthor,
			Date chgDatetime) {
		this.advActionId = advActionId;
		this.advActionName = advActionName;
		this.locInstId = locInstId;
		this.locInstName = locInstName;
		this.CCity = CCity;
		this.creatAuthor = creatAuthor;
		this.crateDatetime = crateDatetime;
		this.chgAuthor = chgAuthor;
		this.chgDatetime = chgDatetime;
	}

	// Property accessors

	public Long getAdvActionId() {
		return this.advActionId;
	}

	public void setAdvActionId(Long advActionId) {
		this.advActionId = advActionId;
	}

	public String getAdvActionName() {
		return this.advActionName;
	}

	public void setAdvActionName(String advActionName) {
		this.advActionName = advActionName;
	}

	public String getLocInstId() {
		return this.locInstId;
	}

	public void setLocInstId(String locInstId) {
		this.locInstId = locInstId;
	}

	public String getLocInstName() {
		return this.locInstName;
	}

	public void setLocInstName(String locInstName) {
		this.locInstName = locInstName;
	}

	public String getCCity() {
		return this.CCity;
	}

	public void setCCity(String CCity) {
		this.CCity = CCity;
	}

	public String getCreatAuthor() {
		return this.creatAuthor;
	}

	public void setCreatAuthor(String creatAuthor) {
		this.creatAuthor = creatAuthor;
	}

	public Date getCrateDatetime() {
		return this.crateDatetime;
	}

	public void setCrateDatetime(Date crateDatetime) {
		this.crateDatetime = crateDatetime;
	}

	public String getChgAuthor() {
		return this.chgAuthor;
	}

	public void setChgAuthor(String chgAuthor) {
		this.chgAuthor = chgAuthor;
	}

	public Date getChgDatetime() {
		return this.chgDatetime;
	}

	public void setChgDatetime(Date chgDatetime) {
		this.chgDatetime = chgDatetime;
	}
}