package com.cib.model;

import java.util.Date;

/**
 * ActionRule generated by MyEclipse Persistence Tools
 */

public class ActionRule implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3917999118084365335L;

	private Long advActionId;

	private String advActionName;

	private String psnInstId;

	private String psnInstName;

	private String CBirthmonth;

	private String CSex;

	private Long CYearMax;

	private Long CYearMin;

	private Long CNewPointMax;

	private Long CNewPointMin;

	private Long CCreditMax;

	private Long CCreditMin;

	private Long CLeftcreditMax;

	private Long CLeftcreditMin;

	private String CCardType;

	private String creatAuthor;

	private Date crateDatetime;

	private String chgAuthor;

	private Date chgDatetime;
	
	/** default constructor */
	public ActionRule() {
	}
	// Constructors
	/** full constructor */
	public ActionRule(Long advActionId, String advActionName,
			String psnInstId, String psnInstName, String CBirthmonth,
			String CSex, Long CYearMax, Long CYearMin, Long CNewPointMax,
			Long CNewPointMin, Long CCreditMax, Long CCreditMin,
			Long CLeftcreditMax, Long CLeftcreditMin, String CCardType,
			String creatAuthor, Date crateDatetime, String chgAuthor,
			Date chgDatetime) {
		this.advActionId = advActionId;
		this.advActionName = advActionName;
		this.psnInstId = psnInstId;
		this.psnInstName = psnInstName;
		this.CBirthmonth = CBirthmonth;
		this.CSex = CSex;
		this.CYearMax = CYearMax;
		this.CYearMin = CYearMin;
		this.CNewPointMax = CNewPointMax;
		this.CNewPointMin = CNewPointMin;
		this.CCreditMax = CCreditMax;
		this.CCreditMin = CCreditMin;
		this.CLeftcreditMax = CLeftcreditMax;
		this.CLeftcreditMin = CLeftcreditMin;
		this.CCardType = CCardType;
		this.creatAuthor = creatAuthor;
		this.crateDatetime = crateDatetime;
		this.chgAuthor = chgAuthor;
		this.chgDatetime = chgDatetime;
	}

	// Property accessors

	public Long getAdvActionId() {
		return this.advActionId;
	}

	public void setAdvActionId(Long advActionId) {
		this.advActionId = advActionId;
	}

	public String getAdvActionName() {
		return this.advActionName;
	}

	public void setAdvActionName(String advActionName) {
		this.advActionName = advActionName;
	}

	public String getPsnInstId() {
		return this.psnInstId;
	}

	public void setPsnInstId(String psnInstId) {
		this.psnInstId = psnInstId;
	}

	public String getPsnInstName() {
		return this.psnInstName;
	}

	public void setPsnInstName(String psnInstName) {
		this.psnInstName = psnInstName;
	}

	public String getCBirthmonth() {
		return this.CBirthmonth;
	}

	public void setCBirthmonth(String CBirthmonth) {
		this.CBirthmonth = CBirthmonth;
	}

	public String getCSex() {
		return this.CSex;
	}

	public void setCSex(String CSex) {
		this.CSex = CSex;
	}

	public Long getCYearMax() {
		return this.CYearMax;
	}

	public void setCYearMax(Long CYearMax) {
		this.CYearMax = CYearMax;
	}

	public Long getCYearMin() {
		return this.CYearMin;
	}

	public void setCYearMin(Long CYearMin) {
		this.CYearMin = CYearMin;
	}

	public Long getCNewPointMax() {
		return this.CNewPointMax;
	}

	public void setCNewPointMax(Long CNewPointMax) {
		this.CNewPointMax = CNewPointMax;
	}

	public Long getCNewPointMin() {
		return this.CNewPointMin;
	}

	public void setCNewPointMin(Long CNewPointMin) {
		this.CNewPointMin = CNewPointMin;
	}

	public Long getCCreditMax() {
		return this.CCreditMax;
	}

	public void setCCreditMax(Long CCreditMax) {
		this.CCreditMax = CCreditMax;
	}

	public Long getCCreditMin() {
		return this.CCreditMin;
	}

	public void setCCreditMin(Long CCreditMin) {
		this.CCreditMin = CCreditMin;
	}

	public Long getCLeftcreditMax() {
		return this.CLeftcreditMax;
	}

	public void setCLeftcreditMax(Long CLeftcreditMax) {
		this.CLeftcreditMax = CLeftcreditMax;
	}

	public Long getCLeftcreditMin() {
		return this.CLeftcreditMin;
	}

	public void setCLeftcreditMin(Long CLeftcreditMin) {
		this.CLeftcreditMin = CLeftcreditMin;
	}

	public String getCCardType() {
		return this.CCardType;
	}

	public void setCCardType(String CCardType) {
		this.CCardType = CCardType;
	}

	public String getCreatAuthor() {
		return this.creatAuthor;
	}

	public void setCreatAuthor(String creatAuthor) {
		this.creatAuthor = creatAuthor;
	}

	public Date getCrateDatetime() {
		return this.crateDatetime;
	}

	public void setCrateDatetime(Date crateDatetime) {
		this.crateDatetime = crateDatetime;
	}

	public String getChgAuthor() {
		return this.chgAuthor;
	}

	public void setChgAuthor(String chgAuthor) {
		this.chgAuthor = chgAuthor;
	}

	public Date getChgDatetime() {
		return this.chgDatetime;
	}

	public void setChgDatetime(Date chgDatetime) {
		this.chgDatetime = chgDatetime;
	}
}