package com.cib.model;

import java.util.Date;

/**
 * 作业管理实体--作业管理表
 * JobMg generated by MyEclipse Persistence Tools
 */

public class JobMg implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -4488053617417208022L;

	private Long jobId;

	private Long batchId;

	private String cardType;

	private Date statementDate;

	private String consolStatus;

	private String dealStatus;

	private Long prtRuleId;

	private Date billingMonth;

	private String dataloadStatus;

	private String streamloadStatus;

	private String estatementStatus;

	private String esendMode;

	private Date esendDatetime;

	private String createAuthor;

	private Date createDatetime;

	private String chgAuthor;

	private Date chgDatetime;

	// Constructors

	/** default constructor */
	public JobMg() {
	}

	/** minimal constructor */
	public JobMg(Long jobId) {
		this.jobId = jobId;
	}

	/** full constructor */
	public JobMg(Long jobId, Long batchId, String cardType, Date statementDate,
			String consolStatus, String dealStatus, Long prtRuleId,
			Date billingMonth, String dataloadStatus, String streamloadStatus,
			String estatementStatus, String esendMode, Date esendDatetime,
			String createAuthor, Date createDatetime, String chgAuthor,
			Date chgDatetime) {
		this.jobId = jobId;
		this.batchId = batchId;
		this.cardType = cardType;
		this.statementDate = statementDate;
		this.consolStatus = consolStatus;
		this.dealStatus = dealStatus;
		this.prtRuleId = prtRuleId;
		this.billingMonth = billingMonth;
		this.dataloadStatus = dataloadStatus;
		this.streamloadStatus = streamloadStatus;
		this.estatementStatus = estatementStatus;
		this.esendMode = esendMode;
		this.esendDatetime = esendDatetime;
		this.createAuthor = createAuthor;
		this.createDatetime = createDatetime;
		this.chgAuthor = chgAuthor;
		this.chgDatetime = chgDatetime;
	}

	// Property accessors

	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	public Long getBatchId() {
		return this.batchId;
	}

	public void setBatchId(Long batchId) {
		this.batchId = batchId;
	}

	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	public Date getStatementDate() {
		return this.statementDate;
	}

	public void setStatementDate(Date statementDate) {
		this.statementDate = statementDate;
	}

	public String getConsolStatus() {
		return this.consolStatus;
	}

	public void setConsolStatus(String consolStatus) {
		this.consolStatus = consolStatus;
	}

	public String getDealStatus() {
		return this.dealStatus;
	}

	public void setDealStatus(String dealStatus) {
		this.dealStatus = dealStatus;
	}

	public Long getPrtRuleId() {
		return this.prtRuleId;
	}

	public void setPrtRuleId(Long prtRuleId) {
		this.prtRuleId = prtRuleId;
	}

	public Date getBillingMonth() {
		return this.billingMonth;
	}

	public void setBillingMonth(Date billingMonth) {
		this.billingMonth = billingMonth;
	}

	public String getDataloadStatus() {
		return this.dataloadStatus;
	}

	public void setDataloadStatus(String dataloadStatus) {
		this.dataloadStatus = dataloadStatus;
	}

	public String getStreamloadStatus() {
		return this.streamloadStatus;
	}

	public void setStreamloadStatus(String streamloadStatus) {
		this.streamloadStatus = streamloadStatus;
	}

	public String getEstatementStatus() {
		return this.estatementStatus;
	}

	public void setEstatementStatus(String estatementStatus) {
		this.estatementStatus = estatementStatus;
	}

	public String getEsendMode() {
		return this.esendMode;
	}

	public void setEsendMode(String esendMode) {
		this.esendMode = esendMode;
	}

	public Date getEsendDatetime() {
		return this.esendDatetime;
	}

	public void setEsendDatetime(Date esendDatetime) {
		this.esendDatetime = esendDatetime;
	}

	public String getCreateAuthor() {
		return this.createAuthor;
	}

	public void setCreateAuthor(String createAuthor) {
		this.createAuthor = createAuthor;
	}

	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public String getChgAuthor() {
		return this.chgAuthor;
	}

	public void setChgAuthor(String chgAuthor) {
		this.chgAuthor = chgAuthor;
	}

	public Date getChgDatetime() {
		return this.chgDatetime;
	}

	public void setChgDatetime(Date chgDatetime) {
		this.chgDatetime = chgDatetime;
	}
}