package com.cib.model;

import java.util.Date;

/**
 * JobPrinting generated by MyEclipse Persistence Tools
 */

public class JobPrinting implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 2751587015015301735L;

	private Long batchId;

	private Long prtRuleId;

	private Date statementDate;

	private String genStatus;

	private String deliverStatus;

	private String staticsStatus;

	private Long printstreamNumber;

	// Constructors

	/** default constructor */
	public JobPrinting() {
	}

	/** minimal constructor */
	public JobPrinting(Long batchId) {
		this.batchId = batchId;
	}

	/** full constructor */
	public JobPrinting(Long batchId, Long prtRuleId, Date statementDate,
			String genStatus, String deliverStatus, String staticsStatus,
			Long printstreamNumber) {
		this.batchId = batchId;
		this.prtRuleId = prtRuleId;
		this.statementDate = statementDate;
		this.genStatus = genStatus;
		this.deliverStatus = deliverStatus;
		this.staticsStatus = staticsStatus;
		this.printstreamNumber = printstreamNumber;
	}

	// Property accessors

	public Long getBatchId() {
		return this.batchId;
	}

	public void setBatchId(Long batchId) {
		this.batchId = batchId;
	}

	public Long getPrtRuleId() {
		return this.prtRuleId;
	}

	public void setPrtRuleId(Long prtRuleId) {
		this.prtRuleId = prtRuleId;
	}

	public Date getStatementDate() {
		return this.statementDate;
	}

	public void setStatementDate(Date statementDate) {
		this.statementDate = statementDate;
	}

	public String getGenStatus() {
		return this.genStatus;
	}

	public void setGenStatus(String genStatus) {
		this.genStatus = genStatus;
	}

	public String getDeliverStatus() {
		return this.deliverStatus;
	}

	public void setDeliverStatus(String deliverStatus) {
		this.deliverStatus = deliverStatus;
	}

	public String getStaticsStatus() {
		return this.staticsStatus;
	}

	public void setStaticsStatus(String staticsStatus) {
		this.staticsStatus = staticsStatus;
	}

	public Long getPrintstreamNumber() {
		return this.printstreamNumber;
	}

	public void setPrintstreamNumber(Long printstreamNumber) {
		this.printstreamNumber = printstreamNumber;
	}

}