package com.cib.model;

/**
 * 城市代码列实体--城市代码列表
 * LocationDic generated by MyEclipse Persistence Tools
 */

public class LocationDic implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -749398493913720533L;

	private String locCode;

	private String branchName;

	private String location;

	// Constructors

	/** default constructor */
	public LocationDic() {
	}

	/** minimal constructor */
	public LocationDic(String locCode) {
		this.locCode = locCode;
	}

	/** full constructor */
	public LocationDic(String locCode, String branchName, String location) {
		this.locCode = locCode;
		this.branchName = branchName;
		this.location = location;
	}

	// Property accessors

	public String getLocCode() {
		return this.locCode;
	}

	public void setLocCode(String locCode) {
		this.locCode = locCode;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}