package com.cib.model;

import java.util.Date;


/**
 * 打印规则实体--打印规则表
 * PrintRule generated by MyEclipse Persistence Tools
 */

public class PrintRule implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 4840524545095369882L;
	private Long prtRuleId;
     private String prtRuleName;
     private Long templateId;
     private Long advActionId;
     private String useFlag;
     private String createAuthor;
     private Date createDatetime;
     private String chgAuthor;
     private Date chgDatetime;


    // Constructors

    /** default constructor */
    public PrintRule() {
    }

	/** minimal constructor */
    public PrintRule(Long prtRuleId) {
        this.prtRuleId = prtRuleId;
    }
    
    /** full constructor */
    public PrintRule(Long prtRuleId, String prtRuleName, Long templateId, Long advActionId, String useFlag, String createAuthor, Date createDatetime, String chgAuthor, Date chgDatetime) {
        this.prtRuleId = prtRuleId;
        this.prtRuleName = prtRuleName;
        this.templateId = templateId;
        this.advActionId = advActionId;
        this.useFlag = useFlag;
        this.createAuthor = createAuthor;
        this.createDatetime = createDatetime;
        this.chgAuthor = chgAuthor;
        this.chgDatetime = chgDatetime;
    }

   
    // Property accessors

    public Long getPrtRuleId() {
        return this.prtRuleId;
    }
    
    public void setPrtRuleId(Long prtRuleId) {
        this.prtRuleId = prtRuleId;
    }

    public String getPrtRuleName() {
        return this.prtRuleName;
    }
    
    public void setPrtRuleName(String prtRuleName) {
        this.prtRuleName = prtRuleName;
    }

    public Long getTemplateId() {
        return this.templateId;
    }
    
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    public Long getAdvActionId() {
        return this.advActionId;
    }
    
    public void setAdvActionId(Long advActionId) {
        this.advActionId = advActionId;
    }

    public String getUseFlag() {
        return this.useFlag;
    }
    
    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    public String getCreateAuthor() {
        return this.createAuthor;
    }
    
    public void setCreateAuthor(String createAuthor) {
        this.createAuthor = createAuthor;
    }

    public Date getCreateDatetime() {
        return this.createDatetime;
    }
    
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    public String getChgAuthor() {
        return this.chgAuthor;
    }
    
    public void setChgAuthor(String chgAuthor) {
        this.chgAuthor = chgAuthor;
    }

    public Date getChgDatetime() {
        return this.chgDatetime;
    }
    
    public void setChgDatetime(Date chgDatetime) {
        this.chgDatetime = chgDatetime;
    }
   








}