package com.cib.model;

/**
 * PrintInstitution generated by MyEclipse Persistence Tools
 */

public class PrintInstitution implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1710575116710875517L;

	private Long institutionId;

	private String institutionName;

	private String institutionState;

	private String ftpServer;

	private String userName;

	private String userPws;

	// Constructors

	/** default constructor */
	public PrintInstitution() {
	}

	/** minimal constructor */
	public PrintInstitution(Long institutionId) {
		this.institutionId = institutionId;
	}

	/** full constructor */
	public PrintInstitution(Long institutionId, String institutionName,
			String institutionState, String ftpServer, String userName,
			String userPws) {
		this.institutionId = institutionId;
		this.institutionName = institutionName;
		this.institutionState = institutionState;
		this.ftpServer = ftpServer;
		this.userName = userName;
		this.userPws = userPws;
	}

	// Property accessors

	public Long getInstitutionId() {
		return this.institutionId;
	}

	public void setInstitutionId(Long institutionId) {
		this.institutionId = institutionId;
	}

	public String getInstitutionName() {
		return this.institutionName;
	}

	public void setInstitutionName(String institutionName) {
		this.institutionName = institutionName;
	}

	public String getInstitutionState() {
		return this.institutionState;
	}

	public void setInstitutionState(String institutionState) {
		this.institutionState = institutionState;
	}

	public String getFtpServer() {
		return this.ftpServer;
	}

	public void setFtpServer(String ftpServer) {
		this.ftpServer = ftpServer;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPws() {
		return this.userPws;
	}

	public void setUserPws(String userPws) {
		this.userPws = userPws;
	}

}