package com.cib.model;

/**
 * 权限管理实体--权限管理表
 * RightMg generated by MyEclipse Persistence Tools
 */

public class RightMg implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -920784815696640742L;

	private Long rightId;

	private String rightName;

	private String rightDesc;

	// Constructors

	/** default constructor */
	public RightMg() {
	}

	/** minimal constructor */
	public RightMg(Long rightId) {
		this.rightId = rightId;
	}

	/** full constructor */
	public RightMg(Long rightId, String rightName, String rightDesc) {
		this.rightId = rightId;
		this.rightName = rightName;
		this.rightDesc = rightDesc;
	}

	// Property accessors

	public Long getRightId() {
		return this.rightId;
	}

	public void setRightId(Long rightId) {
		this.rightId = rightId;
	}

	public String getRightName() {
		return this.rightName;
	}

	public void setRightName(String rightName) {
		this.rightName = rightName;
	}

	public String getRightDesc() {
		return this.rightDesc;
	}

	public void setRightDesc(String rightDesc) {
		this.rightDesc = rightDesc;
	}

}