package com.cib.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 角色管理实体--角色管理表
 * RoleMg generated by MyEclipse Persistence Tools
 */

public class RoleMg implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -8943659247835401493L;

	private Long roleId;

	private String roleName;

	private String roleState;

	private Date createDate;

	private Date modityDate;

	private String roleRight;

	private Set userMgs = new HashSet(0);

	// Constructors

	/** default constructor */
	public RoleMg() {
	}

	/** minimal constructor */
	public RoleMg(Long roleId) {
		this.roleId = roleId;
	}

	/** full constructor */
	public RoleMg(Long roleId, String roleName, String roleState,
			Date createDate, Date modityDate, String roleRight, Set userMgs) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleState = roleState;
		this.createDate = createDate;
		this.modityDate = modityDate;
		this.roleRight = roleRight;
		this.userMgs = userMgs;
	}

	// Property accessors

	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleState() {
		return this.roleState;
	}

	public void setRoleState(String roleState) {
		this.roleState = roleState;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getModityDate() {
		return this.modityDate;
	}

	public void setModityDate(Date modityDate) {
		this.modityDate = modityDate;
	}

	public String getRoleRight() {
		return this.roleRight;
	}

	public void setRoleRight(String roleRight) {
		this.roleRight = roleRight;
	}

	public Set getUserMgs() {
		return this.userMgs;
	}

	public void setUserMgs(Set userMgs) {
		this.userMgs = userMgs;
	}

}