package com.cib.model;

import java.util.Date;

/**
 * TmpMsg generated by MyEclipse Persistence Tools
 */

public class TmpMsg implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 5445861795881051811L;

	private Long templateId;

	private Long recordId;

	private String templateName;

	private String templateFname;

	private String templateFormat;

	private String caFile;

	private String vaultTmpFile;

	private String mailTmpFile;

	private String checkTmpFile;

	private Long msgNumber;

	private Long picNumber;

	private String tmpDesc;

	private Date crateDatetime;

	private Date chgDatetime;

	private String creatAuthor;

	private String chgAuthor;

	// Constructors

	/** default constructor */
	public TmpMsg() {
	}

	/** minimal constructor */
	public TmpMsg(Long templateId) {
		this.templateId = templateId;
	}

	/** full constructor */
	public TmpMsg(Long templateId, Long recordId, String templateName,
			String templateFname, String templateFormat, String caFile,
			String vaultTmpFile, String mailTmpFile, String checkTmpFile,
			Long msgNumber, Long picNumber, String tmpDesc, Date crateDatetime,
			Date chgDatetime, String creatAuthor, String chgAuthor) {
		this.templateId = templateId;
		this.recordId = recordId;
		this.templateName = templateName;
		this.templateFname = templateFname;
		this.templateFormat = templateFormat;
		this.caFile = caFile;
		this.vaultTmpFile = vaultTmpFile;
		this.mailTmpFile = mailTmpFile;
		this.checkTmpFile = checkTmpFile;
		this.msgNumber = msgNumber;
		this.picNumber = picNumber;
		this.tmpDesc = tmpDesc;
		this.crateDatetime = crateDatetime;
		this.chgDatetime = chgDatetime;
		this.creatAuthor = creatAuthor;
		this.chgAuthor = chgAuthor;
	}

	// Property accessors

	public Long getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(Long templateId) {
		this.templateId = templateId;
	}

	public Long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	public String getTemplateFname() {
		return this.templateFname;
	}

	public void setTemplateFname(String templateFname) {
		this.templateFname = templateFname;
	}

	public String getTemplateFormat() {
		return this.templateFormat;
	}

	public void setTemplateFormat(String templateFormat) {
		this.templateFormat = templateFormat;
	}

	public String getCaFile() {
		return this.caFile;
	}

	public void setCaFile(String caFile) {
		this.caFile = caFile;
	}

	public String getVaultTmpFile() {
		return this.vaultTmpFile;
	}

	public void setVaultTmpFile(String vaultTmpFile) {
		this.vaultTmpFile = vaultTmpFile;
	}

	public String getMailTmpFile() {
		return this.mailTmpFile;
	}

	public void setMailTmpFile(String mailTmpFile) {
		this.mailTmpFile = mailTmpFile;
	}

	public String getCheckTmpFile() {
		return this.checkTmpFile;
	}

	public void setCheckTmpFile(String checkTmpFile) {
		this.checkTmpFile = checkTmpFile;
	}

	public Long getMsgNumber() {
		return this.msgNumber;
	}

	public void setMsgNumber(Long msgNumber) {
		this.msgNumber = msgNumber;
	}

	public Long getPicNumber() {
		return this.picNumber;
	}

	public void setPicNumber(Long picNumber) {
		this.picNumber = picNumber;
	}

	public String getTmpDesc() {
		return this.tmpDesc;
	}

	public void setTmpDesc(String tmpDesc) {
		this.tmpDesc = tmpDesc;
	}

	public Date getCrateDatetime() {
		return this.crateDatetime;
	}

	public void setCrateDatetime(Date crateDatetime) {
		this.crateDatetime = crateDatetime;
	}

	public Date getChgDatetime() {
		return this.chgDatetime;
	}

	public void setChgDatetime(Date chgDatetime) {
		this.chgDatetime = chgDatetime;
	}

	public String getCreatAuthor() {
		return this.creatAuthor;
	}

	public void setCreatAuthor(String creatAuthor) {
		this.creatAuthor = creatAuthor;
	}

	public String getChgAuthor() {
		return this.chgAuthor;
	}

	public void setChgAuthor(String chgAuthor) {
		this.chgAuthor = chgAuthor;
	}

}