package com.cib.model;

import java.util.Date;

/**
 * 用户管理实体--用户管理表
 * UserMg generated by MyEclipse Persistence Tools
 */

public class UserMg implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 124079066248514812L;

	private Long userId;

	private RoleMg roleMg;

	private DepartmentMg departmentMg;

	private String userName;

	private String deptName;

	private String roleName;

	private String userPws;

	private String confirmPws;

	private String userLevel;

	private Date createDate;

	private Date latelyDate;

	// Constructors

	/** default constructor */
	public UserMg() {
	}

	/** minimal constructor */
	public UserMg(Long userId, RoleMg roleMg, DepartmentMg departmentMg) {
		this.userId = userId;
		this.roleMg = roleMg;
		this.departmentMg = departmentMg;
	}

	/** full constructor */
	public UserMg(Long userId, RoleMg roleMg, DepartmentMg departmentMg,
			String userName, String deptName, String roleName, String userPws,
			String confirmPws, String userLevel, Date createDate,
			Date latelyDate) {
		this.userId = userId;
		this.roleMg = roleMg;
		this.departmentMg = departmentMg;
		this.userName = userName;
		this.deptName = deptName;
		this.roleName = roleName;
		this.userPws = userPws;
		this.confirmPws = confirmPws;
		this.userLevel = userLevel;
		this.createDate = createDate;
		this.latelyDate = latelyDate;
	}

	// Property accessors

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public RoleMg getRoleMg() {
		return this.roleMg;
	}

	public void setRoleMg(RoleMg roleMg) {
		this.roleMg = roleMg;
	}

	public DepartmentMg getDepartmentMg() {
		return this.departmentMg;
	}

	public void setDepartmentMg(DepartmentMg departmentMg) {
		this.departmentMg = departmentMg;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getUserPws() {
		return this.userPws;
	}

	public void setUserPws(String userPws) {
		this.userPws = userPws;
	}

	public String getConfirmPws() {
		return this.confirmPws;
	}

	public void setConfirmPws(String confirmPws) {
		this.confirmPws = confirmPws;
	}

	public String getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(String userLevel) {
		this.userLevel = userLevel;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLatelyDate() {
		return this.latelyDate;
	}

	public void setLatelyDate(Date latelyDate) {
		this.latelyDate = latelyDate;
	}

}