package com.cib.model;

import java.util.Date;

/**
 * 
 * WithdrawManager generated by MyEclipse Persistence Tools
 */

public class WithdrawManager implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 5110907862096657846L;

	private String cardNo;

	private String billDate;

	private Date exportTime;

	private String option1;

	// Constructors

	/** default constructor */
	public WithdrawManager() {
	}

	/** minimal constructor */
	public WithdrawManager(String cardNo) {
		this.cardNo = cardNo;
	}

	/** full constructor */
	public WithdrawManager(String cardNo, String billDate, Date exportTime,
			String option1) {
		this.cardNo = cardNo;
		this.billDate = billDate;
		this.exportTime = exportTime;
		this.option1 = option1;
	}

	// Property accessors

	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public String getBillDate() {
		return this.billDate;
	}

	public void setBillDate(String billDate) {
		this.billDate = billDate;
	}

	public Date getExportTime() {
		return this.exportTime;
	}

	public void setExportTime(Date exportTime) {
		this.exportTime = exportTime;
	}

	public String getOption1() {
		return this.option1;
	}

	public void setOption1(String option1) {
		this.option1 = option1;
	}

}